name: Build & Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PLUGIN_NAME: stack3d

jobs:
  # Test the code and build packages
  build-packages:
    name: Build Distribution Packages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Nix cache
        uses: cachix/cachix-action@v12
        with:
          name: hyprland
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          
      - name: Build plugin with Nix
        run: |
          echo "Building Hyprland Stack3D plugin with Nix..."
          nix build --print-build-logs
          
          echo "Plugin built successfully"
          ls -la result/lib/
          file result/lib/stack3d.so
          echo "Plugin size: $(du -h result/lib/stack3d.so | cut -f1)"
          
      - name: Create distribution packages
        run: |
          echo "Creating packages for Debian, Fedora, and Arch..."
          ./scripts/build-packages.sh
          
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: distribution-packages
          path: |
            packages/*.tar.gz
            packages/*.deb
            packages/checksums.sha256
          retention-days: 30
          
      - name: Package Summary
        run: |
          echo "Distribution packages built successfully!"
          echo ""
          echo "Built packages:"
          ls -la packages/*.{deb,tar.gz} 2>/dev/null || ls -la packages/*.tar.gz
          echo ""
          echo "Package checksums:"
          cat packages/checksums.sha256
          echo ""
          echo "Plugin binary size: $(du -h result/lib/stack3d.so | cut -f1)"
          echo "Total packages created: $(ls packages/*.{deb,tar.gz} 2>/dev/null | wc -l || ls packages/*.tar.gz | wc -l)"