name: Build Distribution Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PLUGIN_NAME: stack3d

jobs:
  # Build packages for Debian, Fedora, and Arch
  build-packages:
    name: Build Distribution Packages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Create Debian package structure
        run: |
          echo "Creating Debian package structure..."
          mkdir -p packages/debian/hyprland-stack3d-1.0.0/DEBIAN
          mkdir -p packages/debian/hyprland-stack3d-1.0.0/usr/lib/hyprland
          mkdir -p packages/debian/hyprland-stack3d-1.0.0/usr/share/doc/hyprland-stack3d
          
          # Control file
          cat > packages/debian/hyprland-stack3d-1.0.0/DEBIAN/control << EOF
          Package: hyprland-stack3d
          Version: 1.0.0
          Section: x11
          Priority: optional
          Architecture: amd64
          Depends: hyprland
          Maintainer: Stack3D Team <team@example.com>
          Description: 3D stack layout plugin for Hyprland
           Adds 3D perspective stack window management to Hyprland compositor
           with physics-based animations and smooth transitions.
           .
           This package provides advanced window stacking capabilities including:
           * Physics-based animations with spring dynamics
           * Multiple layout modes (grid, cascade, spiral)  
           * Customizable transition effects
           * Bezier curve easing functions
           * Motion blur effects
           * Configurable keybindings
           .
           The plugin integrates seamlessly with Hyprland's existing window
           management system and can be controlled via hyprctl commands.
           .
           To use: Build with 'nix build' then copy stack3d.so to this package.
          EOF
          
          # Copy documentation
          cp hyprland_stack3d_plugin.md packages/debian/hyprland-stack3d-1.0.0/usr/share/doc/hyprland-stack3d/README.md
          cp examples/hyprland.conf packages/debian/hyprland-stack3d-1.0.0/usr/share/doc/hyprland-stack3d/example-hyprland.conf
          
          # Create install instructions
          cat > packages/debian/hyprland-stack3d-1.0.0/usr/share/doc/hyprland-stack3d/INSTALL.md << 'EOF'
          # Installation Instructions
          
          ## Building the Plugin
          
          1. Build the plugin with Nix:
             ```bash
             nix build
             ```
          
          2. Copy the built plugin:
             ```bash
             sudo cp result/lib/stack3d.so /usr/lib/hyprland/
             ```
          
          3. Add to your Hyprland configuration:
             ```
             plugin = /usr/lib/hyprland/stack3d.so
             ```
          
          4. Test with: `hyprctl dispatch stack3d toggle`
          
          ## Configuration
          
          Add plugin settings to your Hyprland config:
          
          ```
          plugin {
              stack3d {
                  enable = true
                  transition_duration = 0.8
                  default_layout = grid
              }
          }
          
          # Keybindings
          bind = SUPER, grave, stack3d, toggle
          bind = SUPER SHIFT, grave, stack3d, cycle_layout
          ```
          EOF
          
      - name: Create Fedora package structure  
        run: |
          echo "Creating Fedora package structure..."
          mkdir -p packages/fedora/hyprland-stack3d-1.0.0/usr/lib64/hyprland
          mkdir -p packages/fedora/hyprland-stack3d-1.0.0/usr/share/doc/hyprland-stack3d
          
          # Copy documentation
          cp hyprland_stack3d_plugin.md packages/fedora/hyprland-stack3d-1.0.0/usr/share/doc/hyprland-stack3d/README.md
          cp examples/hyprland.conf packages/fedora/hyprland-stack3d-1.0.0/usr/share/doc/hyprland-stack3d/example-hyprland.conf
          
          # Create RPM spec file
          cat > packages/fedora/hyprland-stack3d.spec << EOF
          Name:           hyprland-stack3d
          Version:        1.0.0
          Release:        1%{?dist}
          Summary:        3D stack layout plugin for Hyprland
          
          License:        MIT
          URL:            https://github.com/olafkfreund/3Dstack-hyrpland
          
          BuildRequires:  nix
          Requires:       hyprland, pixman, libdrm
          
          %description
          3D stack layout plugin for Hyprland with physics-based animations 
          and smooth transitions.
          
          Features:
          * Physics-based animations with spring dynamics
          * Multiple layout modes (grid, cascade, spiral)
          * Customizable transition effects  
          * Bezier curve easing functions
          * Motion blur effects
          * Configurable keybindings
          
          Build with: nix build
          
          %prep
          %setup -q
          
          %build
          nix build
          
          %install
          mkdir -p %{buildroot}/usr/lib64/hyprland
          mkdir -p %{buildroot}/usr/share/doc/%{name}
          cp result/lib/stack3d.so %{buildroot}/usr/lib64/hyprland/
          cp usr/share/doc/%{name}/* %{buildroot}/usr/share/doc/%{name}/
          
          %files
          /usr/lib64/hyprland/stack3d.so
          /usr/share/doc/%{name}/
          
          %changelog
          * $(date '+%a %b %d %Y') Stack3D Team <team@example.com> - 1.0.0-1
          - Initial release
          - 3D window stacking with physics animations
          - Multiple layout modes and customization options
          EOF
          
      - name: Create Arch package structure
        run: |
          echo "Creating Arch package structure..."
          mkdir -p packages/arch/hyprland-stack3d
          
          # Copy documentation
          cp hyprland_stack3d_plugin.md packages/arch/hyprland-stack3d/README.md
          cp examples/hyprland.conf packages/arch/hyprland-stack3d/example-hyprland.conf
          
          # Create PKGBUILD
          cat > packages/arch/hyprland-stack3d/PKGBUILD << 'EOF'
          # Maintainer: Stack3D Team <team@example.com>
          
          pkgname=hyprland-stack3d
          pkgver=1.0.0
          pkgrel=1
          pkgdesc="3D stack layout plugin for Hyprland"
          arch=('x86_64')
          url="https://github.com/olafkfreund/3Dstack-hyrpland"
          license=('MIT')
          depends=('hyprland' 'pixman' 'libdrm')
          makedepends=('nix')
          source=("https://github.com/olafkfreund/3Dstack-hyrpland/archive/refs/heads/main.zip")
          sha256sums=('SKIP')
          
          build() {
              cd "$srcdir/3Dstack-hyrpland-main"
              nix build
          }
          
          package() {
              cd "$srcdir/3Dstack-hyrpland-main"
              
              # Install plugin binary
              install -Dm755 "result/lib/stack3d.so" "$pkgdir/usr/lib/hyprland/stack3d.so"
              
              # Install documentation
              install -Dm644 "hyprland_stack3d_plugin.md" "$pkgdir/usr/share/doc/$pkgname/README.md"
              install -Dm644 "examples/hyprland.conf" "$pkgdir/usr/share/doc/$pkgname/example-hyprland.conf"
              
              # Create installation instructions
              cat > "$pkgdir/usr/share/doc/$pkgname/INSTALL.md" << 'INSTEOF'
          # hyprland-stack3d Installation
          
          ## Configuration
          
          Add to your Hyprland config:
          
          ```
          plugin = /usr/lib/hyprland/stack3d.so
          
          plugin {
              stack3d {
                  enable = true
                  transition_duration = 0.8
                  default_layout = grid
              }
          }
          
          # Keybindings
          bind = SUPER, grave, stack3d, toggle
          bind = SUPER SHIFT, grave, stack3d, cycle_layout
          ```
          
          ## Usage
          
          - SUPER + grave: Toggle stack view
          - SUPER + SHIFT + grave: Cycle layout modes
          - hyprctl dispatch stack3d toggle: Manual toggle
          
          INSTEOF
          }
          EOF
          
          # Create .SRCINFO
          cat > packages/arch/hyprland-stack3d/.SRCINFO << EOF
          pkgbase = hyprland-stack3d
          	pkgdesc = 3D stack layout plugin for Hyprland
          	pkgver = 1.0.0
          	pkgrel = 1
          	url = https://github.com/olafkfreund/3Dstack-hyrpland
          	arch = x86_64
          	license = MIT
          	makedepends = nix
          	depends = hyprland
          	depends = pixman
          	depends = libdrm
          	source = https://github.com/olafkfreund/3Dstack-hyrpland/archive/refs/heads/main.zip
          	sha256sums = SKIP
          
          pkgname = hyprland-stack3d
          EOF
          
      - name: Create package archives
        run: |
          echo "Creating distribution archives..."
          cd packages
          
          # Create build instructions file
          cat > BUILD.md << 'EOF'
          # Building Hyprland Stack3D Plugin
          
          These packages provide the structure and metadata for packaging the
          Hyprland Stack3D plugin for different distributions.
          
          ## Building the Plugin
          
          Before packaging, you need to build the actual plugin binary:
          
          ```bash
          # Clone the repository
          git clone https://github.com/olafkfreund/3Dstack-hyrpland.git
          cd 3Dstack-hyrpland
          
          # Build with Nix (recommended)
          nix build
          
          # The plugin will be at: result/lib/stack3d.so
          ```
          
          ## Package Contents
          
          - **Debian**: Package structure with control file and documentation
          - **Fedora**: RPM spec file and package structure  
          - **Arch**: PKGBUILD and .SRCINFO for AUR
          
          Each package includes complete installation instructions and examples.
          
          ## Local Building
          
          Use the included build script for complete local packaging:
          
          ```bash
          ./scripts/build-packages.sh
          ```
          
          This will build the plugin with Nix and create complete packages.
          EOF
          
          # Debian package structure
          tar czf hyprland-stack3d-1.0.0-debian.tar.gz debian/ BUILD.md
          
          # Fedora package structure  
          tar czf hyprland-stack3d-1.0.0-fedora.tar.gz fedora/ BUILD.md
          
          # Arch package structure
          tar czf hyprland-stack3d-1.0.0-arch.tar.gz arch/ BUILD.md
          
          echo "Package structures created:"
          ls -la *.tar.gz
          
      - name: Create checksums
        run: |
          cd packages
          sha256sum *.tar.gz > checksums.sha256
          echo "Checksums created:"
          cat checksums.sha256
          
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: distribution-packages
          path: |
            packages/*.tar.gz
            packages/checksums.sha256
            packages/BUILD.md
          retention-days: 30
          
      - name: Package Summary
        run: |
          echo "Distribution packages built successfully!"
          echo ""
          echo "Built packages:"
          ls -la packages/*.tar.gz
          echo ""
          echo "Package checksums:"
          cat packages/checksums.sha256
          echo ""
          echo "Package Contents:"
          echo "  - Debian: Package structure with control file and documentation"
          echo "  - Fedora: RPM spec file and package structure"  
          echo "  - Arch: PKGBUILD and .SRCINFO for AUR"
          echo ""
          echo "Note: Plugin binary must be built separately with 'nix build'"
          echo "Total packages created: $(ls packages/*.tar.gz | wc -l)"

      - name: Create Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          name: "Hyprland Stack3D Plugin v1.0.0"
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            # Hyprland Stack3D Plugin v1.0.0
            
            3D stack layout plugin for Hyprland with physics-based animations and smooth transitions.
            
            ## Features
            
            * Physics-based animations with spring dynamics
            * Multiple layout modes (grid, cascade, spiral, fibonacci)
            * Customizable transition effects and bezier curve easing
            * Motion blur effects and 3D perspective transforms
            * Configurable keybindings and plugin settings
            
            ## Installation
            
            ### Building from Source
            
            ```bash
            # Clone the repository
            git clone https://github.com/olafkfreund/3Dstack-hyrpland.git
            cd 3Dstack-hyrpland
            
            # Build with Nix (recommended)
            nix build
            
            # Copy to Hyprland plugins directory
            cp result/lib/stack3d.so ~/.config/hypr/plugins/
            ```
            
            ### Distribution Packages
            
            Download the appropriate package for your distribution:
            
            - **Debian/Ubuntu**: `hyprland-stack3d-1.0.0-debian.tar.gz`
            - **Fedora/RHEL**: `hyprland-stack3d-1.0.0-fedora.tar.gz`
            - **Arch Linux**: `hyprland-stack3d-1.0.0-arch.tar.gz`
            
            Each package includes complete documentation and installation instructions.
            
            ## Configuration
            
            Add to your Hyprland configuration:
            
            ```
            plugin = ~/.config/hypr/plugins/stack3d.so
            
            plugin {
                stack3d {
                    enable = true
                    transition_duration = 0.8
                    default_layout = grid
                }
            }
            
            # Keybindings
            bind = SUPER, grave, stack3d, toggle
            bind = SUPER SHIFT, grave, stack3d, cycle_layout
            ```
            
            ## Usage
            
            - `SUPER + grave`: Toggle between stack and spread view
            - `SUPER + SHIFT + grave`: Cycle through layout modes
            - `hyprctl dispatch stack3d toggle`: Manual toggle via command
            
            ---
            
            **Package Checksums:** See `checksums.sha256` for file verification.
          files: |
            packages/*.tar.gz
            packages/checksums.sha256
            packages/BUILD.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}