name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        test-type: [unit, integration, memory, coverage]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    
    - name: Setup Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Setup development environment
      run: |
        nix develop --command echo "Development environment ready"
    
    - name: Build plugin
      run: |
        nix develop --command just build
    
    - name: Run unit tests
      if: matrix.test-type == 'unit'
      run: |
        nix develop --command just test-unit
    
    - name: Run integration tests
      if: matrix.test-type == 'integration'
      run: |
        nix develop --command just test-integration
    
    - name: Run memory tests
      if: matrix.test-type == 'memory'
      run: |
        nix develop --command just test-memory
    
    - name: Run coverage tests
      if: matrix.test-type == 'coverage'
      run: |
        nix develop --command just test-coverage
    
    - name: Upload coverage reports
      if: matrix.test-type == 'coverage'
      uses: codecov/codecov-action@v3
      with:
        file: ./tests/*.gcov
        fail_ci_if_error: false

  smoke-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    
    - name: Setup Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Run smoke tests
      run: |
        nix develop --command just test-smoke
    
    - name: Run basic binary tests
      run: |
        nix develop --command just test-basic

  stress-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    
    - name: Setup Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Run stress tests
      run: |
        nix develop --command just test-stress

  nix-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    
    - name: Setup Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Build with Nix
      run: |
        nix build
    
    - name: Run Nix tests
      run: |
        nix build --print-build-logs